/****** TOW WITH VEHICLE  ******/

/**
 * List of class names of vehicles which can tow towables objects.
 */
R3F_LOG_CFG_remorqueurs = 
[
	"SUV_01_base_F",
	"C_SUV_01_F",
	"Offroad_01_base_F",
	"Offroad_02_base_F",
	"C_Offroad_01_F",
	"Van_01_base_F",
	"Van_02_base_F",
	"C_Van_01_transport_F",
	"C_Van_01_box_F",
	"C_Van_01_fuel_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"B_CTRG_LSV_01_light_F",
	"B_T_LSV_01_unarmed_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"B_MRAP_01_F",
	"O_MRAP_02_F",
	"I_MRAP_03_F",
	"LT_01_base_F",
	"I_LT_01_scout_F",
	"B_Boat_Transport_01_F",
	"Wheeled_APC_F",
	"APC_Tracked_01_base_F",
	"APC_Tracked_02_base_F",
	"APC_Tracked_03_base_F",
	"MBT_01_base_F",
	"MBT_02_base_F",
	"MBT_03_base_F",
	"MBT_04_base_F",
	"B_UGV_01_F",
	"B_UGV_01_rcws_F",
	"I_UGV_01_F",
	"I_UGV_01_rcws_F",
	"O_UGV_01_F",
	"O_UGV_01_rcws_F",
	"B_Truck_01_ammo_F",
	"B_Truck_01_fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_Repair_F",
	"O_Truck_03_ammo_f",
	"O_Truck_03_fuel_F",
	"O_Truck_03_medical_F",
	"O_Truck_03_repair_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_fuel_F",
	"I_Truck_02_medical_F"
];

/**
 * List of class names of HEAVY vehicles which can tow heavy towables objects. Takes precedence over R3F_LOG_CFG_remorqueurs
 */
R3F_LOG_CFG_remorqueursH =
[
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Truck_03_base_F",
	"B_Truck_01_mover_F",
	"B_Truck_01_transport_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_box_F",
	"O_Truck_03_device_F",
	"O_Truck_03_transport_F",
	"O_Truck_03_covered_F",
	"I_Truck_02_transport_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_box_F"
];

R3F_LOG_CFG_remorqueurs append R3F_LOG_CFG_remorqueursH;

/**
 * List of class names of objects that can be towed
 */
R3F_LOG_CFG_objets_remorquables =
[
	"Car_F",
	"Ship_F",
	"LT_01_base_F",
	"UAV_03_base_F",
	"Heli_Light_01_base_F",
	"C_Heli_Light_01_civil_F",
	"O_Heli_Light_02_unarmed_F",
	"I_Heli_light_03_unarmed_F",
	"B_Heli_Light_01_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"SUV_01_base_F",
	"C_SUV_01_F",
	"Offroad_01_base_F",
	"Offroad_02_base_F",
	"C_Offroad_01_F",
	"Van_01_base_F",
	"Van_02_base_F",
	"C_Van_01_transport_F",
	"C_Van_01_box_F",
	"C_Van_01_fuel_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"B_CTRG_LSV_01_light_F",
	"B_T_LSV_01_unarmed_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"B_MRAP_01_F",
	"O_MRAP_02_F",
	"I_MRAP_03_F",
	"LT_01_base_F",
	"B_MRAP_01_hmg_F",
	"B_MRAP_01_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_MRAP_03_gmg_F",
	"B_Boat_Transport_01_F",
	"C_Kart_01_F",
	"C_Scooter_Transport_01_F",
	"B_SDV_01_F",
	"O_SDV_01_F",
	"I_SDV_01_F",
	"C_Boat_Civil_01_F",
	"I_G_Quadbike_01_F"
];

/**
 * List of class names of HEAVY towables objects. Takes precedence over R3F_LOG_CFG_objets_remorquables
 */
R3F_LOG_CFG_objets_remorquablesH =
[
	"Plane",
	"I_LT_01_scout_F",
	"Wheeled_APC_F",
	"APC_Tracked_01_base_F",
	"APC_Tracked_02_base_F",
	"APC_Tracked_03_base_F",
	"MBT_01_base_F",
	"MBT_02_base_F",
	"MBT_03_base_F",
	"MBT_04_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Attack_01_base_F",
	"I_Heli_Transport_02_F",
	"Heli_Transport_01_base_F",
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"VTOL_base_F",
	"UAV_05_Base_F",
	"Plane_Fighter_01_Base_F",
	"Plane_Fighter_02_Base_F",
	"Plane_CAS_01_base_F",
	"Plane_CAS_02_base_F",
	"O_APC_Wheeled_02_rcws_v2_F",
	"O_APC_Wheeled_02_rcws_F",
	"B_APC_Wheeled_01_cannon_F",
	"I_APC_Wheeled_03_cannon_F",
	"B_AFV_Wheeled_01_cannon_F",
	"B_AFV_Wheeled_01_up_cannon_F",
	"I_LT_01_cannon_F",
	"I_LT_01_AT_F",
	"I_LT_01_AA_F",
	"B_APC_Tracked_01_CRV_F",
	"B_APC_Tracked_01_rcws_F",
	"I_APC_tracked_03_cannon_F",
	"O_APC_Tracked_02_cannon_F",
	"B_APC_Tracked_01_AA_F",
	"O_APC_Tracked_02_AA_F",
	"B_MBT_01_cannon_F",
	"B_MBT_01_TUSK_F",
	"O_MBT_02_cannon_F",
	"I_MBT_03_cannon_F",
	"O_MBT_04_cannon_F",
	"O_MBT_04_command_F",
	"O_Heli_Transport_04_ammo_F",
	"O_Heli_Transport_04_F",
	"O_Heli_Transport_04_box_F",
	"O_Heli_Transport_04_fuel_F",
	"O_Heli_Transport_04_bench_F",
	"O_Heli_Transport_04_covered_F",
	"O_Heli_Transport_04_medevac_F",
	"O_Heli_Transport_04_repair_F",
	"B_Heli_Transport_03_unarmed_F",
	"B_Heli_Transport_03_F",
	"B_Heli_Transport_01_F",
	"I_Heli_light_03_dynamicLoadout_F",
	"B_Heli_Attack_01_dynamicLoadout_F",
	"O_Heli_Attack_02_dynamicLoadout_F",
	"B_Heli_Light_01_armed_F",
	"B_Heli_Transport_01_F",
	"B_Heli_Attack_01_F",
	"O_Heli_Light_02_F",
	"O_Heli_Attack_02_F",
	"I_Heli_light_03_F",
	"B_T_UAV_03_F",
	"C_Plane_Civil_01_F",
	"I_Plane_Fighter_03_dynamicLoadout_F",
	"I_Plane_Fighter_03_dynamicLoadout_F",
	"I_Plane_Fighter_04_F",
	"B_Plane_Fighter_01_Stealth_F",
	"B_Plane_Fighter_01_F",
	"B_Plane_Fighter_01_F",
	"O_Plane_Fighter_02_Stealth_F",
	"O_Plane_Fighter_02_F",
	"O_Plane_Fighter_02_F",
	"B_Plane_CAS_01_dynamicLoadout_F",
	"O_Plane_CAS_02_dynamicLoadout_F",
	"O_Plane_CAS_02_F",
	"B_T_VTOL_01_infantry_F",
	"B_T_VTOL_01_armed_F",
	"O_T_VTOL_02_infantry_dynamicLoadout_F",
	"O_T_UAV_04_CAS_F",
	"B_UAV_02_dynamicLoadout_F",
	"O_UAV_02_dynamicLoadout_F", 
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_02_dynamicLoadout_F",
	"O_UAV_02_dynamicLoadout_F",
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_02_dynamicLoadout_F",
	"O_UAV_02_dynamicLoadout_F",
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_02_dynamicLoadout_F", 
	"O_UAV_02_dynamicLoadout_F",
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_05_F",
	"B_UGV_01_F",
	"B_UGV_01_rcws_F",
	"I_UGV_01_F",
	"I_UGV_01_rcws_F",
	"O_UGV_01_F",
	"O_UGV_01_rcws_F",
	"B_Truck_01_ammo_F",
	"B_Truck_01_fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_Repair_F",
	"O_Truck_03_ammo_f",
	"O_Truck_03_fuel_F",
	"O_Truck_03_medical_F",
	"O_Truck_03_repair_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_fuel_F",
	"I_Truck_02_medical_F"
];

R3F_LOG_CFG_objets_remorquables append R3F_LOG_CFG_objets_remorquablesH;

/****** LIFT WITH VEHICLE  ******/

/**
 * List of class names of air vehicles which can lift liftables objects.
 */
R3F_LOG_CFG_heliporteurs =
[
	//"Helicopter_Base_F"
	//"C_Heli_Light_01_civil_F"
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"Heli_Attack_01_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Transport_01_base_F",
	"Heli_Light_01_base_F",
	"C_Heli_Light_01_civil_F",
	"O_Heli_Light_02_unarmed_F",
	"I_Heli_light_03_unarmed_F",
	"I_Heli_Transport_02_F",
	"B_Heli_Transport_01_F",
	"B_Heli_Light_01_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"I_Heli_light_03_dynamicLoadout_F",
	"B_Heli_Attack_01_dynamicLoadout_F",
	"O_Heli_Attack_02_dynamicLoadout_F",
	"O_Heli_Light_02_dynamicLoadout_F",
	"B_Heli_Light_01_armed_F", 
	"O_Heli_Attack_02_F",
	"I_Heli_light_03_F",
	"B_Heli_Transport_03_F", 
	"I_Heli_Transport_02_F",
	"O_Heli_Transport_04_ammo_F",
	"O_Heli_Transport_04_fuel_F",
	"O_Heli_Transport_04_repair_F",
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"Heli_Attack_01_base_F",
	"O_Heli_Transport_04_box_F",
	"O_Heli_Transport_04_bench_F",
	"O_Heli_Transport_04_covered_F",
	"O_Heli_Transport_04_medevac_F"
];

/**
 * List of class names of HEAVY air vehicles which can lift heavy liftables objects. Takes precedence over R3F_LOG_CFG_objets_remorquables
 */
R3F_LOG_CFG_heliporteursH =
[

	"B_Heli_Transport_03_unarmed_F",
	"O_Heli_Transport_04_F"


];

R3F_LOG_CFG_heliporteurs append R3F_LOG_CFG_heliporteursH;

/**
 * List of class names of liftable objects.
 */
R3F_LOG_CFG_objets_heliportables =
[
	"Car_F",
	"Ship_F",
	"Plane",
	"LT_01_base_F",
	"UAV_03_base_F",
	"Heli_Light_01_base_F",
	"C_Heli_Light_01_civil_F",
	"O_Heli_Light_02_unarmed_F",
	"I_Heli_light_03_unarmed_F",
	"I_Heli_Transport_02_F",
	"B_Heli_Light_01_F",
	"Heli_Light_02_base_F",
	"Heli_light_03_base_F",
	"Heli_Attack_01_base_F",
	"SUV_01_base_F",
	"C_SUV_01_F",
	"Offroad_01_base_F",
	"Offroad_02_base_F",
	"C_Offroad_01_F",
	"Van_01_base_F",
	"Van_02_base_F",
	"C_Van_01_transport_F",
	"C_Van_01_box_F",
	"C_Van_01_fuel_F",
	"LSV_01_base_F",
	"LSV_02_base_F",
	"B_CTRG_LSV_01_light_F",
	"B_T_LSV_01_unarmed_F",
	"MRAP_01_base_F",
	"MRAP_02_base_F",
	"MRAP_03_base_F",
	"B_MRAP_01_F",
	"O_MRAP_02_F",
	"I_MRAP_03_F",
	"LT_01_base_F",
	"I_LT_01_scout_F",
	"B_Boat_Transport_01_F",
	"C_Kart_01_F",
	"C_Scooter_Transport_01_F",
	"B_SDV_01_F",
	"O_SDV_01_F",
	"I_SDV_01_F",
	"C_Boat_Civil_01_F",
	"I_G_Quadbike_01_F"
];

/**
 * List of class names of HEAVY liftables objects. Takes precedence over R3F_LOG_CFG_objets_heliportables
 */
R3F_LOG_CFG_objets_heliportablesH =
[
	"I_G_Offroad_01_armed_F",
	"I_G_Offroad_01_AT_F",
	"C_Van_01_transport_F",
	"C_Van_01_box_F",
	"C_Van_01_fuel_F",
	"C_Van_02_vehicle_F",
	"C_Van_02_transport_F",
	"B_GEN_Van_02_vehicle_F",
	"B_GEN_Van_02_transport_F",
	"C_Van_02_medevac_F",
	"C_Van_02_service_F",
	"Wheeled_APC_F",
	"APC_Tracked_01_base_F",
	"APC_Tracked_02_base_F",
	"APC_Tracked_03_base_F",
	"MBT_01_base_F",
	"MBT_02_base_F",
	"MBT_03_base_F",
	"MBT_04_base_F",
	"Heli_Attack_02_base_F",
	"Heli_Attack_01_base_F",
	"I_Heli_Transport_02_F",
	"Heli_Transport_01_base_F",
	"Heli_Transport_02_base_F",
	"Heli_Transport_03_base_F",
	"Heli_Transport_04_base_F",
	"VTOL_base_F",
	"UAV_05_Base_F",
	"Plane_Fighter_01_Base_F",
	"Plane_Fighter_02_Base_F",
	"Plane_CAS_01_base_F",
	"Plane_CAS_02_base_F",
	"B_MRAP_01_hmg_F",
	"B_MRAP_01_gmg_F",
	"O_MRAP_02_hmg_F",
	"O_MRAP_02_gmg_F",
	"I_MRAP_03_hmg_F",
	"I_MRAP_03_gmg_F",
	"O_APC_Wheeled_02_rcws_v2_F",
	"O_APC_Wheeled_02_rcws_F",
	"B_APC_Wheeled_01_cannon_F",
	"I_APC_Wheeled_03_cannon_F",
	"B_AFV_Wheeled_01_cannon_F",
	"B_AFV_Wheeled_01_up_cannon_F",
	"I_LT_01_cannon_F",
	"I_LT_01_AT_F",
	"I_LT_01_AA_F",
	"B_APC_Tracked_01_CRV_F",
	"B_APC_Tracked_01_rcws_F",
	"I_APC_tracked_03_cannon_F",
	"O_APC_Tracked_02_cannon_F",
	"B_APC_Tracked_01_AA_F",
	"O_APC_Tracked_02_AA_F",
	"B_MBT_01_cannon_F",
	"B_MBT_01_TUSK_F",
	"O_MBT_02_cannon_F",
	"I_MBT_03_cannon_F",
	"O_MBT_04_cannon_F",
	"O_MBT_04_command_F",
	"O_Heli_Transport_04_ammo_F",
	"O_Heli_Transport_04_F",
	"O_Heli_Transport_04_box_F",
	"O_Heli_Transport_04_fuel_F",
	"O_Heli_Transport_04_bench_F",
	"O_Heli_Transport_04_covered_F",
	"O_Heli_Transport_04_medevac_F",
	"O_Heli_Transport_04_repair_F",
	"B_Heli_Transport_03_unarmed_F",
	"B_Heli_Transport_03_F",
	"B_Heli_Transport_01_F",
	"I_Heli_light_03_dynamicLoadout_F",
	"B_Heli_Attack_01_dynamicLoadout_F",
	"O_Heli_Attack_02_dynamicLoadout_F",
	"B_Heli_Light_01_armed_F",
	"B_Heli_Transport_01_F",
	"B_Heli_Attack_01_F",
	"O_Heli_Light_02_F",
	"O_Heli_Attack_02_F",
	"I_Heli_light_03_F",
	"B_T_UAV_03_F",
	"C_Plane_Civil_01_F",
	"I_Plane_Fighter_03_dynamicLoadout_F",
	"I_Plane_Fighter_03_dynamicLoadout_F",
	"I_Plane_Fighter_04_F",
	"B_Plane_Fighter_01_Stealth_F",
	"B_Plane_Fighter_01_F",
	"B_Plane_Fighter_01_F",
	"O_Plane_Fighter_02_Stealth_F",
	"O_Plane_Fighter_02_F",
	"O_Plane_Fighter_02_F",
	"B_Plane_CAS_01_dynamicLoadout_F",
	"O_Plane_CAS_02_dynamicLoadout_F",
	"O_Plane_CAS_02_F",
	"B_T_VTOL_01_infantry_F",
	"B_T_VTOL_01_armed_F",
	"O_T_VTOL_02_infantry_dynamicLoadout_F",
	"O_T_UAV_04_CAS_F",
	"B_UAV_02_dynamicLoadout_F",
	"O_UAV_02_dynamicLoadout_F", 
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_02_dynamicLoadout_F",
	"O_UAV_02_dynamicLoadout_F",
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_02_dynamicLoadout_F",
	"O_UAV_02_dynamicLoadout_F",
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_02_dynamicLoadout_F", 
	"O_UAV_02_dynamicLoadout_F",
	"I_UAV_02_dynamicLoadout_F",
	"B_UAV_05_F",
	"B_UGV_01_F",
	"B_UGV_01_rcws_F",
	"I_UGV_01_F",
	"I_UGV_01_rcws_F",
	"O_UGV_01_F",
	"O_UGV_01_rcws_F",
	"B_SAM_System_03_F",
	"O_SAM_System_04_F",
	"B_Radar_System_01_F",
	"B_Truck_01_ammo_F",
	"B_Truck_01_fuel_F",
	"B_Truck_01_medical_F",
	"B_Truck_01_Repair_F",
	"O_Truck_03_ammo_f",
	"O_Truck_03_fuel_F",
	"O_Truck_03_medical_F",
	"O_Truck_03_repair_F",
	"I_Truck_02_ammo_F",
	"I_Truck_02_fuel_F",
	"I_Truck_02_medical_F",
	"Truck_01_base_F",
	"Truck_02_base_F",
	"Truck_03_base_F",
	"B_Truck_01_mover_F",
	"B_Truck_01_transport_F",
	"B_Truck_01_covered_F",
	"B_Truck_01_box_F",
	"O_Truck_03_device_F",
	"O_Truck_03_transport_F",
	"O_Truck_03_covered_F",
	"I_Truck_02_transport_F",
	"I_Truck_02_covered_F",
	"I_Truck_02_box_F"
];

R3F_LOG_CFG_objets_heliportables append R3F_LOG_CFG_objets_heliportablesH;


/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/


/**
 * List of class names of (ground or air) vehicles which can transport transportables objects.
 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
 */
R3F_LOG_CFG_transporteurs =
[
	["Quadbike_01_base_F", 5],
	["UGV_01_base_F", 10],
	["Hatchback_01_base_F", 10],
	["SUV_01_base_F", 20],
	["Offroad_01_base_F", 30],
	["Offroad_02_base_F", 20],
	["Van_01_base_F", 40],
	["Van_02_base_F", 50],
	["LSV_01_base_F", 15],
	["LSV_02_base_F", 15],
	["MRAP_01_base_F", 20],
	["MRAP_02_base_F", 20],
	["MRAP_03_base_F", 20],
	["B_Truck_01_box_F", 150],
	["Truck_F", 75],
	["Wheeled_APC_F", 30],
	["LT_01_base_F", 10],
	["Tank_F", 30],
	["Scooter_Transport_01_base_F", 5],
	["SDV_01_base_F", 10],
	["Rubber_duck_base_F", 10],
	["Boat_Civil_01_base_F", 10],
	["Boat_Transport_02_base_F", 15],
	["Boat_Armed_01_base_F", 20],
	["Heli_Light_01_base_F", 10],
	["Heli_Light_02_base_F", 20],
	["Heli_light_03_base_F", 20],
	["Heli_Transport_01_base_F", 25],
	["Heli_Transport_02_base_F", 30],
	["Heli_Transport_03_base_F", 30],
	["Heli_Transport_04_base_F", 30],
	["Heli_Attack_01_base_F", 10],
	["Heli_Attack_02_base_F", 20],
	["Plane_Civil_01_base_F", 5],
	["VTOL_01_base_F", 50],
	["VTOL_02_base_F", 30]
];


R3F_LOG_CFG_objets_transportables =
[
	["Static_Designator_01_base_F", 2],
	["Static_Designator_02_base_F", 2],
	["StaticWeapon", 5],
	["Box_NATO_AmmoVeh_F", 10],
	["B_supplyCrate_F", 5],
	["ReammoBox_F", 3],
	["Kart_01_Base_F", 5],
	["Quadbike_01_base_F", 10],
	["Rubber_duck_base_F", 10],
	["UAV_01_base_F", 2],
	["UAV_06_base_F", 2],
	["Land_PierLadder_F", 3],
	["Land_BagBunker_Large_F", 10],
	["Land_BagBunker_Small_F", 5],
	["Land_BagBunker_Tower_F", 7],
	["Land_BagFence_Corner_F", 2],
	["Land_BagFence_End_F", 2],
	["Land_BagFence_Long_F", 3],
	["Land_BagFence_Round_F", 2],
	["Land_BagFence_Short_F", 2],
	["Land_BarGate_F", 3],
	["Land_Canal_WallSmall_10m_F", 4],
	["Land_Canal_Wall_Stairs_F", 3],
	["Land_CargoBox_V1_F", 5],
	["Land_Cargo_Patrol_V1_F", 7],
	["Land_Cargo_Tower_V1_F", 30],
	["Land_CncBarrier_F", 4],
	["Land_CncBarrierMedium_F", 4],
	["Land_CncBarrierMedium4_F", 4],
	["Land_CncShelter_F", 2],
	["Land_CncWall1_F", 3],
	["Land_CncWall4_F", 5],
	["Land_Crash_barrier_F", 5],
	["Land_HBarrierBig_F", 5],
	["Land_HBarrierTower_F", 8],
	["Land_HBarrierWall4_F", 4],
	["Land_HBarrierWall6_F", 6],
	["Land_HBarrier_1_F", 3],
	["Land_HBarrier_3_F", 4],
	["Land_HBarrier_5_F", 5],
	["Land_LampHarbour_F", 2],
	["Land_LampShabby_F", 2],
	["Land_MetalBarrel_F", 2],
	["Land_Mil_ConcreteWall_F", 5],
	["Land_Mil_WallBig_4m_F", 5],
	["Land_Obstacle_Ramp_F", 5],
	["Land_Pipes_large_F", 5],
	["Land_RampConcreteHigh_F", 6],
	["Land_RampConcrete_F", 5],
	["Land_Razorwire_F", 5],
	["Land_Sacks_goods_F", 2],
	["Land_Scaffolding_F", 5],
	["Land_Shoot_House_Wall_F", 3],
	["Land_Stone_8m_F", 5],
	["Land_ToiletBox_F", 2],
	["Land_BarrelWater_F", 2]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

R3F_LOG_CFG_objets_deplacables =
[
	"StaticWeapon",
	"ReammoBox_F",
	"Kart_01_Base_F",
	"Quadbike_01_base_F",
	"Rubber_duck_base_F",
	"SDV_01_base_F",
	"UAV_01_base_F",
	"UAV_06_base_F",
	"Land_PierLadder_F",
	"Land_BagBunker_Large_F",
	"Land_BagBunker_Small_F",
	"Land_BagBunker_Tower_F",
	"Land_BagFence_Corner_F",
	"Land_BagFence_End_F",
	"Land_BagFence_Long_F",
	"Land_BagFence_Round_F",
	"Land_BagFence_Short_F",
	"Land_BarGate_F",
	"Land_Canal_WallSmall_10m_F",
	"Land_Canal_Wall_Stairs_F",
	"Land_CargoBox_V1_F",
	"Land_Cargo_Patrol_V1_F",
	"Land_Cargo_Tower_V1_F",
	"Land_CncBarrier_F",
	"Land_CncBarrierMedium_F",
	"Land_CncBarrierMedium4_F",
	"Land_CncShelter_F",
	"Land_CncWall1_F",
	"Land_CncWall4_F",
	"Land_Crash_barrier_F",
	"Land_HBarrierBig_F",
	"Land_HBarrierTower_F",
	"Land_HBarrierWall4_F",
	"Land_HBarrierWall6_F",
	"Land_HBarrier_1_F",
	"Land_HBarrier_3_F",
	"Land_HBarrier_5_F",
	"Land_LampHarbour_F",
	"Land_LampShabby_F",
	"Land_MetalBarrel_F",
	"Land_Mil_ConcreteWall_F",
	"Land_Mil_WallBig_4m_F",
	"Land_Obstacle_Ramp_F",
	"Land_Pipes_large_F",
	"Land_RampConcreteHigh_F",
	"Land_RampConcrete_F",
	"Land_Razorwire_F",
	"Land_Sacks_goods_F",
	"Land_Scaffolding_F",
	"Land_Shoot_House_Wall_F",
	"Land_Stone_8m_F",
	"Land_ToiletBox_F",
	"Land_BarrelWater_F"
];
